# _config.yml

# bundle exec jekyll build
# bundle exec jekyll clean 
# bundle exec jekyll serve

# Site settings
title: Eagle Rex
subtitle: Dare to Soar
description: Eagle Rex description
author: Sebastian Rousseau
theme-color: "#000"
background_color: "#fff"
lang: en
locale: en_gb
email: hello@eaglerex.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eaglerex.com" # the base hostname & protocol for your site

# Social Media settings
twitter_username: eaglerex
twitter_creator: wwdseb
github_username: sebastienrousseau
author_facebook: eaglerex
facebook_username: eaglerex
facebook_id: 10156052650356913
linkedin_username: eaglerex
google_analytics: G-X7J1L6Q2D2

# Set the source folder
source: source

# Build settings
encoding: utf-8
repository: sebastienrousseau/eaglerex.com
markdown: CommonMark

# Installed plugins 
plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-sitemap

# Plugins settings

compress_html:
  blanklines: false
  clippings: all
  comments: all
  endings: all
  profile: true
  startings: all

feed:
  path: atom.xml

# Responsive images
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 500
    - width: 250
    - width: 125     
  strip: true
  base_path: assets/images/image-icon
  cache: true
  output_path_format: assets/images/%{width}/%{basename}

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  compression: false
  gzip: false  
  sources:
    - assets/fonts
    - assets/icons
    - assets/images
    - assets/javascripts
    - assets/stylesheets
  caching:
    enabled: true
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
  compress:
    css: '/assets/styles/*.css'
    img: '/assets/**/*.{jpg,png}'
    js: '/assets/js/*.js'

include:
  - .htaccess
  - assets
  - _pages
excerpt_separator: <!--more-->
keep_files:
  - .git
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .jekyll-cache
  - .sass-cache
  - .travis.yml
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Capfile
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - README.md
  - tmp
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - yarn.lock
